
name = input("Pick a name")
noun = input("pick a person or place")
job = input("pick a job")
place = input("pick a place")
building = input("pick a building")
monster = input("pick a monster")
item = input("pick a item")
print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
print(f"There once was a guy named {name} the {noun}.")
print(f"Ever since he was young he wanted to be a raider.")
print(f"So {name} raided his village.")
print(f"The villagers banished him and he became a {job}.")
print(f"But it was boring so {name} decided to go to {place}.")
print(f"In the {place} there was a {building}.")
print(f"{name} decided to go inside the {building}.")
print(f"There {name} found a {monster} and his lost family relic, the {item}.")
print(f"The {monster} charged and {name} rolled out of the way grabbing the {item}.")
print(f"{name} threw the {item} at the {monster} which exploded into a bunch of {noun}s.")
print(f"So {name} became a hero and thats how he got his name of the {noun}.")
print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ")